import { AsyncLocalStorage } from 'node:async_hooks'

export interface LogContext {
  requestId: string
  userId?: string
}

// A single store for the entire app; each request has its own scope.
const storage = new AsyncLocalStorage<LogContext>()

/**
 * Open a new context scope and run `fn` inside.
 * Any async code generated by `fn` will see `ctx`.
 */
export const runWithContext = <T>(ctx: LogContext, fn: () => T): T => {
  return storage.run(ctx, fn)
}

/** Get the current context; return undefined if outside the request (e.g., at startup). */
export const getContext = (): LogContext | undefined => {
  return storage.getStore()
}

/** Attach userId to the current context (call after authentication is complete). */
export const setUserId = (userId?: string) => {
  const ctx = storage.getStore()
  if (ctx && userId) ctx.userId = userId
}
